In [156]:
import pandas as pd

In [157]:
import requests
from bs4 import BeautifulSoup
import numpy as np

In [158]:
import requests
from bs4 import BeautifulSoup

url = "https://en.wikipedia.org/wiki/Python_(programming_language)"

headers = {
    "User-Agent": "MyWikipediaScraper/1.0 (student project; your_email@example.com)"
}

response = requests.get(url, headers=headers)

print(response.status_code)

soup = BeautifulSoup(response.text, "lxml")

print(soup.title.text)

200
Python (programming language) - Wikipedia

In [159]:
# Infobox table find karo
infobox = soup.find("table", class_="infobox")

data = {}

if infobox:
    rows = infobox.find_all("tr")

    for row in rows:
        heading = row.find("th")
        value = row.find("td")

        if heading and value:
            data[heading.text.strip()] = value.text.strip()

# Dictionary print karo
data

{'Paradigm': 'Multi-paradigm: object-oriented,[1] procedural (imperative), functional, structured, reflective',
 'Designed\xa0by': 'Guido van Rossum',
 'Developer': 'Python Software Foundation',
 'First\xa0appeared': '20\xa0February 1991; 35 years ago\xa0(1991-02-20)[2]',
 'Stable release': '3.14.6[3]\xa0\n   / 10 June 2026; 43 days ago\xa0(10 June 2026)',
 'Typing discipline': 'Duck, dynamic, strong;[4] optional type annotations[a]',
 'Memory management': 'Garbage-collected',
 'OS': 'Cross-platform[b]',
 'License': 'Python Software Foundation License',
 'Filename extensions': '.py,[11] .pyc,[12] .pyd,[13] .pyi,[14] .pyw,[15] .pyz[16]',
 'Website': 'python.org'}

In [160]:
import pandas as pd

df = pd.DataFrame(
    list(data.items()),
    columns=["Feature", "Information"]
)

df

                Feature                                        Information
0              Paradigm  Multi-paradigm: object-oriented,[1] procedural...
1           Designed by                                   Guido van Rossum
2             Developer                         Python Software Foundation
3        First appeared     20 February 1991; 35 years ago (1991-02-20)[2]
4        Stable release  3.14.6[3] \n   / 10 June 2026; 43 days ago (10...
5     Typing discipline  Duck, dynamic, strong;[4] optional type annota...
6     Memory management                                  Garbage-collected
7                    OS                                  Cross-platform[b]
8               License                 Python Software Foundation License
9   Filename extensions  .py,[11] .pyc,[12] .pyd,[13] .pyi,[14] .pyw,[1...
10              Website                                         python.org

In [161]:
df["Information"] = (
    df["Information"]
    .str.replace("\xa0", " ", regex=False)
    .str.replace("\n", " ", regex=False)
    .str.strip()
)

df

                Feature                                        Information
0              Paradigm  Multi-paradigm: object-oriented,[1] procedural...
1           Designed by                                   Guido van Rossum
2             Developer                         Python Software Foundation
3        First appeared     20 February 1991; 35 years ago (1991-02-20)[2]
4        Stable release  3.14.6[3]     / 10 June 2026; 43 days ago (10 ...
5     Typing discipline  Duck, dynamic, strong;[4] optional type annota...
6     Memory management                                  Garbage-collected
7                    OS                                  Cross-platform[b]
8               License                 Python Software Foundation License
9   Filename extensions  .py,[11] .pyc,[12] .pyd,[13] .pyi,[14] .pyw,[1...
10              Website                                         python.org

In [162]:
df.to_csv(
    "python_infobox.csv",
    index=False
)

print("CSV Saved Successfully")

CSV Saved Successfully

In [163]:
df.shape

(11, 2)

In [164]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Feature      11 non-null     object
 1   Information  11 non-null     object
dtypes: object(2)
memory usage: 308.0+ bytes

In [165]:
df.head()

          Feature                                        Information
0        Paradigm  Multi-paradigm: object-oriented,[1] procedural...
1     Designed by                                   Guido van Rossum
2       Developer                         Python Software Foundation
3  First appeared     20 February 1991; 35 years ago (1991-02-20)[2]
4  Stable release  3.14.6[3]     / 10 June 2026; 43 days ago (10 ...

In [166]:
df.tail()

                Feature                                        Information
6     Memory management                                  Garbage-collected
7                    OS                                  Cross-platform[b]
8               License                 Python Software Foundation License
9   Filename extensions  .py,[11] .pyc,[12] .pyd,[13] .pyi,[14] .pyw,[1...
10              Website                                         python.org

In [167]:
headings = []

for h in soup.find_all("h2"):
    headings.append(h.get_text(strip=True))

heading_df = pd.DataFrame({
    "Section": headings
})

heading_df

                           Section
0                         Contents
1                          History
2   Design philosophy and features
3             Syntax and semantics
4                    Code examples
5                        Libraries
6         Development environments
7                  Implementations
8             Language development
9                           Naming
10  Languages influenced by Python
11                        See also
12                           Notes
13                      References
14                 Further reading
15                  External links

In [168]:
paragraphs = []

for p in soup.find_all("p"):
    text = p.get_text(" ", strip=True)

    if text:
        paragraphs.append(text)


para_df = pd.DataFrame({
    "Paragraph": paragraphs
})

para_df.head()

                                           Paragraph
0  Python is a high-level , general-purpose progr...
1  Guido van Rossum began working on Python in th...
2  Python is widely taught as an introductory pro...
3  Python was conceived in the late 1980s [ 11 ] ...
4  The name Python derives from the British comed...

In [169]:
para_df.to_csv(
    "python_article.csv",
    index=False
)

print("Article Saved")

Article Saved

In [132]:
df.shape

(11, 2)

In [170]:
df.head()

          Feature                                        Information
0        Paradigm  Multi-paradigm: object-oriented,[1] procedural...
1     Designed by                                   Guido van Rossum
2       Developer                         Python Software Foundation
3  First appeared     20 February 1991; 35 years ago (1991-02-20)[2]
4  Stable release  3.14.6[3]     / 10 June 2026; 43 days ago (10 ...

In [171]:
api_url = "https://en.wikipedia.org/w/api.php"

params = {
    "action": "query",
    "format": "json",
    "list": "categorymembers",
    "cmtitle": "Category:Countries",
    "cmlimit": 100
}


response = requests.get(
    api_url,
    params=params,
    headers=headers
)

result = response.json()

result.keys()

dict_keys(['batchcomplete', 'query'])

In [172]:
countries = []

for item in result["query"]["categorymembers"]:
    countries.append(item["title"])


print(len(countries))
print(countries[:20])

23
['Portal:Countries', 'Country', 'List of country groupings', 'List of modern great powers', 'Category:Countries by continent', 'Category:Countries by form of government', 'Category:Countries by international organization', 'Category:Countries by status', 'Category:Categories by country', 'Category:Outlines of countries', 'Category:Lists of countries', 'Category:Works about countries', 'Category:City-states', 'Category:Country classifications', 'Category:Country codes', 'Category:Country lockdowns', 'Category:Dependent territories', 'Category:Former countries', 'Category:Island countries', 'Category:Landlocked countries']

In [173]:
def scrape_country(country):

    url = "https://en.wikipedia.org/wiki/" + country.replace(" ", "_")

    response = requests.get(
        url,
        headers=headers
    )


    soup = BeautifulSoup(
        response.text,
        "lxml"
    )


    data = {}

    data["Country"] = country


    infobox = soup.find(
        "table",
        class_="infobox"
    )


    if infobox:

        rows = infobox.find_all("tr")


        for row in rows:

            key = row.find("th")
            value = row.find("td")


            if key and value:

                data[key.text.strip()] = (
                    value.text
                    .replace("\n"," ")
                    .strip()
                )


    return data

In [ ]:
country_data = []


for country in countries:

    print("Scraping:", country)

    try:

        data = scrape_country(country)

        country_data.append(data)

        time.sleep(1)


    except Exception as e:

        print("Error:", e)

Scraping: Portal:Countries

In [138]:
df = pd.DataFrame(country_data)

df.head()

                           Country
0                 Portal:Countries
1                          Country
2        List of country groupings
3      List of modern great powers
4  Category:Countries by continent

In [139]:
df.shape

(23, 1)

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  23 non-null     object
dtypes: object(1)
memory usage: 316.0+ bytes

In [ ]:
df.head()

In [142]:
df.tail()

                          Country
18      Category:Island countries
19  Category:Landlocked countries
20         Category:Country names
21    Category:Proposed countries
22             Category:Republics

In [143]:
df.to_csv(
    "countries_wikipedia_data.csv",
    index=False
)

print("Scraping Completed Successfully")

Scraping Completed Successfully

In [144]:
import os

os.path.exists("countries_wikipedia_data.csv")

True

In [145]:
df_check = pd.read_csv("countries_wikipedia_data.csv")

df_check.head()

                           Country
0                 Portal:Countries
1                          Country
2        List of country groupings
3      List of modern great powers
4  Category:Countries by continent

In [146]:
df = df.drop_duplicates()

print(df.shape)

(23, 1)

In [147]:
df.isnull().sum()

Country    0
dtype: int64

In [148]:
(df.isnull().sum() / len(df)) * 100

Country    0.0
dtype: float64

In [149]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

df.columns

Index(['country'], dtype='object')

In [150]:
df = df.apply(
    lambda x: x.str.strip() if x.dtype=="object" else x
)

In [151]:
import matplotlib.pyplot as plt
import seaborn as sns

In [153]:
df.columns

Index(['country'], dtype='object')

In [154]:
df.head()

                           country
0                 Portal:Countries
1                          Country
2        List of country groupings
3      List of modern great powers
4  Category:Countries by continent