In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv(r'C:\Users\SHUBHAM\Downloads\customer.csv')
df

    age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
16   59    Male     Poor        UG       Yes
17   22  Female     Poor        UG       Yes
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
20   57  Female  Average    School       Yes
21   32    Male  Average        PG        No
22   18  Female     Poor        PG       Yes
23   96  Female     Good    School        No
24   16  Female  Average        PG       Yes
25   57  Female     Good    School        No
26   53  Female     Poor        PG        No
27   69  Female     Poor        PG        No
28   48    Male     Poor    School        No
29   83  Female  Average        UG       Yes
30   73    Male  Average        UG        No
31   22  Female     Poor    School       Yes
32   92    Male  Average        UG       Yes
33   89  Female     Good        PG       Yes
34   86    Male  Average    School        No
35   74    Male     Poor    School       Yes
36   34  Female     Good        UG       Yes
37   94    Male  Average        PG       Yes
38   45  Female     Good    School        No
39   76    Male     Poor        PG        No
40   39    Male     Good    School        No
41   23    Male     Good        PG       Yes
42   30  Female     Good        PG       Yes
43   27    Male     Poor        PG        No
44   77  Female  Average        UG        No
45   61    Male     Poor        PG       Yes
46   64  Female     Poor        PG        No
47   38  Female     Good        PG       Yes
48   39  Female     Good        UG       Yes
49   25  Female     Good        UG        No

In [3]:
df.sample(5)

    age  gender   review education purchased
33   89  Female     Good        PG       Yes
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
15   75    Male     Poor        UG        No
11   74    Male     Good        UG       Yes

In [4]:
df=df.iloc[:,2:]

In [5]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2 )

In [10]:
x_train

     review education
11     Good        UG
40     Good    School
24  Average        PG
49     Good        UG
27     Poor        PG
44  Average        UG
29  Average        UG
30  Average        UG
12     Poor    School
32  Average        UG
41     Good        PG
8   Average        UG
6      Good    School
46     Poor        PG
38     Good    School
36     Good        UG
42     Good        PG
25     Good    School
18     Good    School
14     Poor        PG
31     Poor    School
37  Average        PG
15     Poor        UG
7      Poor    School
20  Average    School
34  Average    School
43     Poor        PG
0   Average    School
10     Good        UG
4   Average        UG
9      Good        UG
35     Poor    School
47     Good        PG
21  Average        PG
26     Poor        PG
39     Poor        PG
1      Poor        UG
19     Poor        PG
33     Good        PG
45     Poor        PG

In [11]:
y_train

11    Yes
40     No
24    Yes
49     No
27     No
44     No
29    Yes
30     No
12     No
32    Yes
41    Yes
8      No
6      No
46     No
38     No
36    Yes
42    Yes
25     No
18     No
14    Yes
31    Yes
37    Yes
15     No
7     Yes
20    Yes
34     No
43     No
0      No
10    Yes
4      No
9     Yes
35    Yes
47    Yes
21     No
26     No
39     No
1      No
19    Yes
33    Yes
45    Yes
Name: purchased, dtype: object

In [13]:

from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [17]:

x_train = oe.transform(x_train)
x_train

array([[2., 1.],
       [2., 0.],
       [1., 2.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [2., 2.],
       [2., 0.],
       [2., 0.],
       [0., 2.],
       [0., 0.],
       [1., 2.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [2., 2.],
       [1., 2.],
       [0., 2.],
       [0., 2.],
       [0., 1.],
       [0., 2.],
       [2., 2.],
       [0., 2.]])

In [18]:

oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [19]:
x_train

array([[2., 1.],
       [2., 0.],
       [1., 2.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [2., 2.],
       [2., 0.],
       [2., 0.],
       [0., 2.],
       [0., 0.],
       [1., 2.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [2., 2.],
       [1., 2.],
       [0., 2.],
       [0., 2.],
       [0., 1.],
       [0., 2.],
       [2., 2.],
       [0., 2.]])

In [20]:
from sklearn.preprocessing import LabelEncoder

In [21]:
le=LabelEncoder()

In [22]:
le.fit(y_train)

LabelEncoder()

In [23]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [24]:

y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [25]:
y_train

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1])